### ISSUE TITLE
Skipping password saving since the user is likely prompted with Android Autofill.

### ISSUE THREAD

**Issue by tdcolvin** [tdcolvin/ExampleCredentialSignIn#2]
I try your example it work.  I write but not use compose. but still fail in step save credential.
Have any settings with project.?
`Credential save error: During save password, found password failure response from one tap 16: Skipping password saving since the user is likely prompted with Android Autofill.-- android.credentials.CreateCredentialException.TYPE_UNKNOWN
                                                                                                    androidx.credentials.exceptions.CreateCredentialUnknownException: During save password, found password failure response from one tap 16: Skipping password saving since the user is likely prompted with Android Autofill.
                                                                                                    	at androidx.credentials.playservices.controllers.CredentialProviderBaseController$Companion.createCredentialExceptionTypeToException$credentials_play_services_auth_release(CredentialProviderBaseController.kt:108)
                                                                                                    	at androidx.credentials.playservices.controllers.CreatePassword.CredentialProviderCreatePasswordController$resultReceiver$1$onReceiveResult$1.invoke(CredentialProviderCreatePasswordController.kt:82)
                                                                                                    	at androidx.credentials.playservices.controllers.CreatePassword.CredentialProviderCreatePasswordController$resultReceiver$1$onReceiveResult$1.invoke(CredentialProviderCreatePasswordController.kt:82)
                                                                                                    	at androidx.credentials.playservices.controllers.CredentialProviderController.maybeReportErrorFromResultReceiver(CredentialProviderController.kt:157)
                                                                                                    	at androidx.credentials.playservices.controllers.CreatePassword.CredentialProviderCreatePasswordController.access$maybeReportErrorFromResultReceiver(CredentialProviderCreatePasswordController.kt:46)
                                                                                                    	at androidx.credentials.playservices.controllers.CreatePassword.CredentialProviderCreatePasswordController$resultReceiver$1.onReceiveResult(CredentialProviderCreatePasswordController.kt:81)
                                                                                                    	at android.os.ResultReceiver$MyRunnable.run(ResultReceiver.java:50)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7898)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
`

_Originally posted by @tranvantung95 in https://github.com/tdcolvin/ExampleCredentialSignIn/issues/1#issuecomment-1465140395_

**Comment by tdcolvin** [comment]
Looks like Credential Manager clashes with autofill - and I guess it makes sense that it would, since they both have something in common.
According to this answer:
https://stackoverflow.com/questions/1959576/turn-off-autosuggest-for-edittext/56320742#56320742
...using `android:importantForAutofill="no"` in your XML should turn off Autofill. If the error message you pasted is as helpful as it seems, that should solve the issue.

**Comment by tranvantung95** [comment]
i'm already add `android:importantForAutofill="no"` to my xml, but it not solve my issue.

**Comment by MirzaUkas** [comment]
I'm also having trouble with Compose. Is it possible there are any custom settings about autofill that I need to be aware of? @tdcolvin 

in official docs they are already mentioned https://developer.android.com/training/sign-in/passkeys#troubleshoot

_"This error occurs only on Android 13 and lower, and only if Google is the Autofill provider. In this case, users see a save prompt from Autofill and the password is saved to the Google Password Manager. Note that the credentials saved using Autofill with Google are bi-directionally shared with Credential Manager API. As a result, this error can be safely ignored."_

So, what do you think about this?

**Comment by tdcolvin** [comment]
Hmm, not aware of anything general. If you post code and tell me what the specifics are I can try to debug

**Comment by MirzaUkas** [comment]
After debugging and checking other related issues in stackoverflow, I've tried to make sure autofill can work together with credential manager. Unfortunately, it doesn't work. We need to choose one, either autofill or credential manager. So, I disabled autofill in my application (as you suggested above). Because my application uses compose, so I disable programmatically like this, instead of using property in xml. So far it works.

```kotlin
 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            this.getSystemService(AutofillManager::class.java)?.disableAutofillServices()
            this.window.decorView.importantForAutofill =
                View.IMPORTANT_FOR_AUTOFILL_NO_EXCLUDE_DESCENDANTS
        }
```
